name: Test and Check

run-name: Running tests and checks for policies

on: [push]

jobs:
  Test-And-Check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Run OPA Tests
        run: make test

      - name: Run OPA Check
        run: make check
